# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hateru_cocos2dx-desktop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hateru_cocos2dx-desktop

end

target 'hateru_cocos2dx-mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Firebase
  pod 'Firebase/Core', '5.18.0'
  pod 'Firebase/Auth', '5.18.0'
  pod 'Firebase/Database', '5.18.0'

  # Google
  pod 'GoogleSignIn'

  # Facebook
  pod 'FBSDKLoginKit'

  # Twitter

end
